parameters:
    ibexa.site_access.config.default.search.pagination.limit: 10

    ibexa.site_access.config.site_group.search_view:
        full:
            default:
                template: "@@ibexadesign/search/index.html.twig"
                match: []
