parameters:
    ezsettings.default.search.pagination.limit: 10

    ezsettings.site_group.search_view:
        full:
            default:
                template: "@@ibexadesign/search/index.html.twig"
                match: []
