ibexa.search:
    path: /search
    methods: [GET]
    controller: 'Ibexa\Bundle\Search\Controller\SearchController::searchAction'

ibexa.search.suggestion:
    path: /suggestion
    methods: [GET]
    controller: 'Ibexa\Bundle\Search\Controller\SuggestionController::suggestAction'
    options:
        expose: true
