ibexa.search:
    path: /search
    methods: ['GET']
    defaults:
      _controller: 'Ibexa\Bundle\Search\Controller\SearchController::searchAction'

ibexa.search_autocomplete:
    path: /autocomplete
    methods: ['GET']
    defaults:
      _controller: 'Ibexa\Bundle\Search\Controller\SearchAutoCompleteController::suggestAction'
