imports:
  - { resource: forms.yaml }
  - { resource: views.yaml }

services:
  _defaults:
      autoconfigure: true
      autowire: true
      public: false

  Ibexa\Bundle\Search\Controller\SearchController:
      tags:
          - controller.service_arguments

  Ibexa\Search\Mapper\PagerSearchContentToDataMapper:
      arguments:
          $contentTypeService: '@ezpublish.api.service.content_type'
          $userService: '@ezpublish.api.service.user'
          $userLanguagePreferenceProvider: '@Ibexa\Core\MVC\Symfony\Locale\UserLanguagePreferenceProvider'
          $translationHelper: '@ezpublish.translation_helper'
          $languageService: '@ezpublish.api.service.language'

  Ibexa\Search\QueryType\SearchQueryType:
      arguments:
          $searchService: '@ezpublish.api.service.search'
