services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\Search\Twig\Extension\SearchFacetsExtension:
        tags:
            -   name: twig.extension
