services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ibexa.search.suggestion.serializer:
        class: Symfony\Component\Serializer\Serializer
        autoconfigure: false
        arguments:
            $normalizers:
                - '@Ibexa\Search\Serializer\Normalizer\Suggestion\ContentSuggestionNormalizer'
                - '@Ibexa\Search\Serializer\Normalizer\Suggestion\ParentLocationNormalizer'
            $encoders:
                - '@serializer.encoder.json'

    Ibexa\Search\Serializer\Normalizer\Suggestion\ContentSuggestionNormalizer:
        autoconfigure: false
        tags:
            - { name: 'ibexa.search.serializer.normalizer' }

    Ibexa\Search\Serializer\Normalizer\Suggestion\ParentLocationCollectionNormalizer:
        autoconfigure: false
        tags:
              - { name: 'ibexa.search.serializer.normalizer' }

    Ibexa\Search\Serializer\Normalizer\Suggestion\ParentLocationNormalizer:
        autoconfigure: false
        tags:
              - { name: 'ibexa.search.serializer.normalizer' }
