services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Search\Serializer\Normalizer\Suggestion\ContentSuggestionNormalizer:
        autoconfigure: false
        tags:
            - { name: 'ibexa.search.serializer.normalizer' }

    Ibexa\Search\Serializer\Normalizer\Suggestion\ParentLocationCollectionNormalizer:
        autoconfigure: false
        tags:
              - { name: 'ibexa.search.serializer.normalizer' }

    Ibexa\Search\Serializer\Normalizer\Suggestion\ParentLocationNormalizer:
        autoconfigure: false
        tags:
              - { name: 'ibexa.search.serializer.normalizer' }

    Ibexa\Search\Serializer\SuggestionSerializerFactory: ~

    Ibexa\Search\Serializer\SuggestionSerializer:
        factory: '@Ibexa\Search\Serializer\SuggestionSerializerFactory'
        arguments:
            $normalizers: !tagged_iterator { tag: 'ibexa.search.serializer.normalizer' }
