parameters:
    ibexa.site_access.config.default.search.suggestion.min_query_length: 3
    ibexa.site_access.config.default.search.suggestion.result_limit: 5

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\Search\EventDispatcher\EventListener\ContentSuggestionSubscriber: ~

    Ibexa\Search\Mapper\SearchHitToContentSuggestionMapper: ~

    Ibexa\Contracts\Search\Mapper\SearchHitToContentSuggestionMapperInterface: '@Ibexa\Search\Mapper\SearchHitToContentSuggestionMapper'

    Ibexa\Search\Service\SuggestionService: ~

    Ibexa\Contracts\Search\Service\SuggestionServiceInterface: '@Ibexa\Search\Service\SuggestionService'

    Ibexa\Search\Service\Event\SuggestionService:
        decorates: Ibexa\Contracts\Search\Service\SuggestionServiceInterface

    Ibexa\Search\Provider\ParentLocationProvider: ~

    Ibexa\Contracts\Search\Provider\ParentLocationProviderInterface: '@Ibexa\Search\Provider\ParentLocationProvider'
